### ISSUE TITLE
0.15?

### ISSUE THREAD

**Issue by abordoli** [MrP123/BridgeRailway#4]
Any plans to port this up to 0.15?
Regards,
~B

**Comment by MrP123** [comment]
The mod was updated to work with Factorio 0.15 by [d3x0r](https://github.com/d3x0r) just a couple of hours ago!

I myself wouldn't have updated the mod, as there is really no need for it anymore with the addition of landfill to the Factorio base game.

**Comment by abordoli** [comment]
Thanks! I, personally, like the look of the "bridge over water" concept.

Can mod Boats go under it? I guess I'll see soon enough...
